name: commit

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set node
        uses: actions/setup-node@v2

        with:
          node-version: '16'

      - name: install
        run: npm install

      - name: run
        run: npm run test
        env:
          CK: ${{secrets.CK}}
          ID: ${{secrets.ID}}
          UID: ${{secrets.UID}}
          SIGN: ${{secrets.SIGN}}

        