name: commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: '3 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set node
        uses: actions/setup-node@v2

        with:
          node-version: '16'

      - name: install
        run: npm install

      - name: run
        run: npm run sign
        env:
          CK: ${{secrets.CK}}
          ID: ${{secrets.ID}}
          UID: ${{secrets.UID}}
          SIGN: ${{secrets.SIGN}}

        